apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llama-model.fullname" . }}
  labels:
    app: {{ include "llama-model.name" . }}
    chart: {{ include "llama-model.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "llama-model.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "llama-model.name" . }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        - name: {{ .Values.imagePullSecrets | first }}
        {{- end }}
      containers:
        - name: {{ include "llama-model.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          command: {{ toJson .Values.command }}
          args: {{ toJson .Values.args }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.service.port }} # Ensure this is a valid port
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.service.port }} # Ensure this is a valid port
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts: {{ toYaml .Values.volumeMounts | nindent 12 }}
      volumes: {{ toYaml .Values.volumes | nindent 8 }}

